sudo: false
dist: trusty
language: php
notifications:
  email:
    on_success: never
    on_failure: never
before_script:
- |
  if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
    phpenv config-rm xdebug.ini
  else
    echo "xdebug.ini does not exist"
  fi
- |
  if [[ ! -z "$WP_VERSION" ]] ; then
    bash tests/bin/prepare-env.sh
    composer global require "phpunit/phpunit=4.8.*|5.7.*"
  fi
jobs:
  include:
    - stage: test
      php: 5.6
      env: WP_VERSION=latest SENSEI_VERSION=master
      script:
        - ./tests/bin/travis-phpunit.sh
    - stage: test
      php: 7.0
      env: WP_VERSION=latest SENSEI_VERSION=master
      script:
        - ./tests/bin/travis-phpunit.sh
    - stage: test
      php: 7.1
      env: WP_VERSION=latest SENSEI_VERSION=master
      script:
        - ./tests/bin/travis-phpunit.sh
    - stage: test
      php: 7.2
      env: WP_VERSION=latest SENSEI_VERSION=master
      script:
        - ./tests/bin/travis-phpunit.sh
    - stage: test
      php: 7.3
      env: WP_VERSION=latest SENSEI_VERSION=master
      script:
        - ./tests/bin/travis-phpunit.sh
    - stage: test
      php: 7.4
      env: WP_VERSION=latest SENSEI_VERSION=master
      script:
        - ./tests/bin/travis-phpunit.sh
