dist: trusty

language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.4

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=5.0 WP_MULTISITE=0
    - WP_VERSION=5.0 WP_MULTISITE=1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
